=== andersonhonorio/xmlschema.js/demo/pokemon.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://paulwardrip.github.io/xmlschema.js/demo/pokemon">

    <xs:element name="trainer" type="Trainer" />

    <xs:attributeGroup name="PokemonAttributes">
        <xs:attribute name="level" use="required" />
        <xs:attribute name="hpmax" use="required" />
        <xs:attribute name="hp" use="required" />
    </xs:attributeGroup>

    <xs:complexType name="ItemType">
        <xs:attribute name="inventory" use="required" />
    </xs:complexType>

    <xs:complexType name="Trainer">
        <xs:sequence>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="potion" type="ItemType" />
                <xs:element name="revive" type="ItemType" />
                <xs:element name="pokeball" type="ItemType" />
            </xs:choice>
            <xs:element name="team">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="pokemon" type="TrainerPokemon" minOccurs="1" maxOccurs="6" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Pokemon">
        <xs:attribute name="id" use="required" />
        <xs:sequence>
            <xs:element name="name" type="xs:string" maxOccurs="1" minOccurs="1" />
            <xs:element name="type" type="PokemonType" minOccurs="1" maxOccurs="2" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TrainerPokemon">
        <xs:attributeGroup ref="PokemonAttributes"/>
        <xs:complexContent>
            <xs:extension base="Pokemon">
                <xs:sequence>
                    <xs:element name="nickname" maxOccurs="1" minOccurs="0" />
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:simpleType name="PokemonType">
        <xs:restriction>
            <xs:enumeration value="normal" />
            <xs:enumeration value="fighting"/>
            <xs:enumeration value="flying"/>
            <xs:enumeration value="poison"/>
            <xs:enumeration value="ground"/>
            <xs:enumeration value="rock"/>
            <xs:enumeration value="bug"/>
            <xs:enumeration value="ghost"/>
            <xs:enumeration value="steel"/>
            <xs:enumeration value="fire"/>
            <xs:enumeration value="fire"/>
            <xs:enumeration value="water"/>
            <xs:enumeration value="grass"/>
            <xs:enumeration value="electric"/>
            <xs:enumeration value="psychic"/>
            <xs:enumeration value="ice"/>
            <xs:enumeration value="dragon"/>
            <xs:enumeration value="dark"/>
            <xs:enumeration value="fairy"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:unique name="PokemonID">
        <xs:selector xpath="//team//pokemon" />
        <xs:field xpath="@id" />
    </xs:unique>
</xs:schema>

=== andersonhonorio/xmlschema.js/demo/pokemon.xml
<trainer xmlns="https://paulwardrip.github.io/xmlschema.js/demo/pokemon"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://paulwardrip.github.io/xmlschema.js/demo/pokemon pokemon.xsd">

    <pokeball inventory="2" />
    <potion inventory="1" />
    <revive inventory="3" />

    <team>
        <pokemon id="1" level="4" hp="100" hpmax="100">
            <name>Bulbasaur</name>
            <type>poison</type>
            <type>grass</type>
        </pokemon>
        <pokemon id="1">
            <name>Bulbasaur</name>
            <type>poison</type>
            <type>grass</type>
        </pokemon>
    </team>
</trainer>
